# Generated by Django 5.2.7 on 2025-11-22 12:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Incoming Stock'), ('OUT', 'Outgoing Stock')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity added or removed', max_digits=10)),
                ('movement_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='invoices.product')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
