# Generated by Django 5.2.7 on 2025-12-25 08:31

from django.db import migrations


def populate_default_business(apps, schema_editor):
    """Create a default business and assign it to all existing records"""
    Business = apps.get_model('invoices', 'Business')
    Product = apps.get_model('invoices', 'Product')
    Invoice = apps.get_model('invoices', 'Invoice')
    StockMovement = apps.get_model('invoices', 'StockMovement')
    BusinessMembership = apps.get_model('invoices', 'BusinessMembership')
    User = apps.get_model('auth', 'User')
    
    # Create default business
    default_business, created = Business.objects.get_or_create(
        name='Default Business',
        defaults={'description': 'Auto-created default business for existing data'}
    )
    
    # Assign default business to all existing products
    Product.objects.filter(business__isnull=True).update(business=default_business)
    
    # Assign default business to all existing invoices
    Invoice.objects.filter(business__isnull=True).update(business=default_business)
    
    # Assign default business to all existing stock movements
    StockMovement.objects.filter(business__isnull=True).update(business=default_business)
    
    # Add all existing users to the default business
    for user in User.objects.all():
        BusinessMembership.objects.get_or_create(
            user=user,
            business=default_business,
            defaults={'role': 'admin' if user.is_staff else 'member'}
        )


def reverse_populate(apps, schema_editor):
    """Remove default business on migration reversal"""
    Business = apps.get_model('invoices', 'Business')
    Business.objects.filter(name='Default Business').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_business_businessmembership_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_default_business, reverse_populate),
    ]
