# Generated by Django 5.2.7 on 2025-12-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_business_alter_product_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online Payment')], default='cash', max_length=10),
        ),
    ]
